const document = {
  generality: {
    title: "2021年度中层领导班子绩效考核任务书",
    company: "计算机学院",
    tableData: [
      {
        index: {
          rowSpan: 3,
          key: 1,
          value: 1,
          show: true,
          index: 1,
        },
        firstTarget: {
          rowSpan: 3,
          key: 2,
          value: "共性指标 （20分） 无 需填写",
          show: true,
          index: 1,
        },
        target_index: {
          rowSpan: 1,
          key: 3,
          value: 1,
          show: true,
          index: 1,
        },
        target: {
          rowSpan: 1,
          key: 4,
          value: "工作目标1",
          show: true,
          index: 1,
        },
        department: {
          rowSpan: 1,
          key: 5,
          value: "考核部门1",
          show: true,
        },
        score: {
          rowSpan: 1,
          key: 6,
          value: "score",
          show: true,
        },
        grade: {
          rowSpan: 1,
          key: 7,
          value: "grade",
          show: true,
        },
        remarks: {
          rowSpan: 1,
          key: 8,
          value: "remarks",
          show: true,
        },
      },
      {
        index: {
          rowSpan: 0,
          key: 9,
          value: 1,
          show: false,
          index: 1,
        },
        firstTarget: {
          rowSpan: 0,
          key: 10,
          value: "共性指标 （20分） 无 需填写",
          show: false,
          index: 1,
        },
        target_index: {
          rowSpan: 1,
          key: 11,
          value: 1,
          show: true,
          index: 2,
        },
        target: {
          rowSpan: 1,
          key: 12,
          value: "工作目标2",
          show: true,
          index: 1,
        },
        department: {
          rowSpan: 1,
          key: 13,
          value: "考核部门2",
          show: true,
        },
        score: {
          rowSpan: 1,
          key: 14,
          value: "score",
          show: true,
        },
        grade: {
          rowSpan: 1,
          key: 15,
          value: "grade",
          show: true,
        },
        remarks: {
          rowSpan: 1,
          key: 16,
          value: 222,
          show: true,
        },
      },
      {
        index: {
          rowSpan: 0,
          key: 17,
          value: 1,
          show: false,
          index: 1,
        },
        firstTarget: {
          rowSpan: 0,
          key: 18,
          value: "共性指标 （20分） 无 需填写",
          show: false,
          index: 1,
        },
        target_index: {
          rowSpan: 1,
          key: 19,
          value: 3,
          show: true,
          index: 3,
        },
        target: {
          rowSpan: 1,
          key: 20,
          value: "工作目标3",
          show: true,
          index: 1,
        },
        department: {
          rowSpan: 1,
          key: 21,
          value: "考核部门3",
          show: true,
        },
        score: {
          rowSpan: 1,
          key: 22,
          value: "score",
          show: true,
        },
        grade: {
          rowSpan: 1,
          key: 23,
          value: "grade",
          show: true,
        },
        remarks: {
          rowSpan: 1,
          key: 24,
          value: "remarks",
          show: true,
        },
      },
    ],
  },
  commonly: {
    tableData: [],
  },
  // {
  //   index: {
  //     rowSpan: 1,
  //     key: "132",
  //     value: 2,
  //     show: true,
  //     index: 1,
  //   },
  //   firstTarget: {
  //     rowSpan: 1,
  //     key: "132",
  //     value: `一般性指标 （65分） 仔细核对
  //     2021年一般 性指标填报 （教务处下 达指标数量 ，可根据
  //     2021年工作 微量调整),
  //     并给每条数 据赋分`,
  //     show: true,
  //     index: 1,
  //   },
  //   target_index: {
  //     rowSpan: 1,
  //     key: 1,
  //     value: 1,
  //     show: true,
  //     index: 3,
  //   },
  //   target: {
  //     rowSpan: 1,
  //     key: 1,
  //     value: "工作目标3",
  //     show: true,
  //     index: 1,
  //   },
  //   department: {
  //     rowSpan: 1,
  //     key: "423",
  //     value: "考核部门3",
  //     show: true,
  //   },
  //   score: {
  //     rowSpan: 1,
  //     key: "score",
  //     value: 123,
  //     show: true,
  //   },
  //   grade: {
  //     rowSpan: 1,
  //     key: "grade",
  //     value: 123,
  //     show: true,
  //   },
  //   remarks: {
  //     rowSpan: 1,
  //     key: "remarks",
  //     value: 222,
  //     show: true,
  //   },
  // },
};
export { document };

// {
//   key: '1',
//   name: 'John Brown',
//   age: 32,
//   tel: '0571-22098909',
//   phone: 18889898989,
//   address: 'New York No. 1 Lake Park',
// },
// {
//   key: '2',
//   name: 'Jim Green',
//   tel: '0571-22098333',
//   phone: 18889898888,
//   age: 42,
//   address: 'London No. 1 Lake Park',
// },
// {
//   key: '3',
//   name: 'Joe Black',
//   age: 32,
//   tel: '0575-22098909',
//   phone: 18900010002,
//   address: 'Sidney No. 1 Lake Park',
// },
// {
//   key: '4',
//   name: 'Jim Red',
//   age: 18,
//   tel: '0575-22098909',
//   phone: 18900010002,
//   address: 'London No. 2 Lake Park',
// },
// {
//   key: '5',
//   name: 'Jake White',
//   age: 18,
//   tel: '0575-22098909',
//   phone: 18900010002,
//   address: 'Dublin No. 2 Lake Park',
// },
